In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype="int16")

In [5]:
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
b.ndim

2

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
c = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[3.0,2.0,1.0]])

In [17]:
# Get Type
a.dtype

dtype('int16')

In [25]:
# Get Size
a.itemsize

8

In [22]:
# Get total size
a.size

6

In [24]:
# Get total size
a.nbytes

6

### Accessing/Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
# Get a specific element
a[1, 5]

13

In [29]:
a[1, -2]

13

In [30]:
# Get a specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [37]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [45]:
a[1,5] = 20
a[:,0]

array([1, 8])

In [63]:
b = np.array([
    [
        [1,2],[3,4]]
    ,[
        [5,6],[7,8]]])

b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [61]:
# Get specific element (word outsdide in)
b[0,1,:]

array([3, 4])

In [68]:
#replace
b[:,1,:] = [[9,9],[8,8]]

b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of arrays

In [73]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [77]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [79]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [81]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.2808898 , 0.93288719, 0.64610733],
        [0.68122845, 0.49204176, 0.63042778]],

       [[0.69034649, 0.3226498 , 0.86675917],
        [0.80107329, 0.25879377, 0.30446252]],

       [[0.37441024, 0.81537222, 0.61855277],
        [0.04500511, 0.36831185, 0.46788541]],

       [[0.02088471, 0.26777024, 0.75925919],
        [0.0255961 , 0.19980434, 0.73525027]]])

In [82]:
np.random.random_sample(a.shape)

array([[0.72073864, 0.51065966, 0.48167045, 0.07140249, 0.39547299,
        0.19266497, 0.11094953],
       [0.47892487, 0.6874014 , 0.3773992 , 0.70208171, 0.99220684,
        0.63306853, 0.44387106]])

In [83]:
np.random.rand(4,2)

array([[0.91567899, 0.55907052],
       [0.86926497, 0.59451477],
       [0.39793429, 0.05404677],
       [0.05235131, 0.66655382]])

In [87]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[5, 0, 1],
       [5, 5, 6],
       [2, 1, 3]])

In [88]:
np.random.randint(-4,8, size=(3,3))

array([[ 2,  5,  2],
       [ 7,  6,  6],
       [-4, -2,  3]])

In [91]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [117]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!!

In [121]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])

In [122]:
a

array([1, 2, 3])

### Mathematics

In [138]:
a = np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [139]:
a += 2

In [140]:
a - 2

array([1, 2, 3, 4])

In [141]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [142]:
b = np.array([1,0,1,0])

In [143]:
a + b

array([4, 4, 6, 6])

In [144]:
a ** 2

array([ 9, 16, 25, 36])

In [146]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [147]:
# Take the cos
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear Algebra

In [157]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [156]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [155]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [161]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [163]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.min(stats)

1

In [165]:
np.max(stats)

6

In [166]:
np.max(stats, axis=0)

array([4, 5, 6])

In [170]:
np.max(stats, axis=0)

array([4, 5, 6])

In [171]:
np.sum(stats)

21

In [175]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [181]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [184]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [191]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((2,4))

after

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [196]:
# Vertically stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [202]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [205]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Loead Data from File

In [213]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
         32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
         50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
         68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [215]:
filedata >= 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [216]:
filedata[filedata > 50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108], dtype=int32)

In [219]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [224]:
np.all(filedata > 50, axis=1)

array([False, False, False,  True,  True,  True])

In [230]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False, False, False, False]])

In [232]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])